
import PageTemplate from '../components/page-template';
import Content from '../components/content';

export default function App (): JSX.Element {
    return (PageTemplate(Content(contentMarkdown, 'markdown')));
};

let contentMarkdown = `
## TODO

- Redo how pages are built from markdown files generated by \`nbconvert\` using \`Next-MDX\` instead.
  - This is necessary to handle interactive graphics on this site in the future.
  - Interactive graphics, like tables, tend to be implemented as nested HTML blocks.
  - This is naturally the \`MDX\` file format.
`;
